package com.candido.server.exception._common;

public enum EnumExceptionName {
    ERROR_AUTH_VERIFICATION,

    ERROR_VALIDATION_INVALID_EXCEPTION_CONFIGURATION,

    ERROR_VALIDATION_INVALID_EMAIL,
    ERROR_VALIDATION_EMAIL_CAN_NOT_BE_EMPTY,
    ERROR_VALIDATION_FIRST_NAME_CAN_NOT_BE_EMPTY,
    ERROR_VALIDATION_LAST_NAME_CAN_NOT_BE_EMPTY,
    ERROR_VALIDATION_TEMPORARY_CODE_CAN_NOT_BE_EMPTY,
    ERROR_VALIDATION_INVALID_TEMPORARY_CODE,
    ERROR_VALIDATION_TOKEN_CAN_NOT_BE_EMPTY,
    ERROR_VALIDATION_INVALID_TOKEN,
    ERROR_VALIDATION_ACCOUNT_SETTINGS_KEY_VALUE,

    ERROR_VALIDATION_PASSWORDS_DO_NOT_MATCH,
    ERROR_VALIDATION_PASSWORD_CAN_NOT_BE_EMPTY,
    ERROR_VALIDATION_CONFIRM_PASSWORD_CAN_NOT_BE_EMPTY,
    ERROR_VALIDATION_CURRENT_PASSWORD_DOES_NOT_MATCH,

    ERROR_BUSINESS_DUPLICATE_USERNAME_ACCOUNT,
    ERROR_BUSINESS_ACCOUNT_NOT_FOUND,
    ERROR_BUSINESS_ACCOUNT_DISABLED,
    ERROR_BUSINESS_ACCOUNT_ROLE_NOT_FOUND,
    ERROR_BUSINESS_USER_NOT_FOUND,
    ERROR_BUSINESS_ACCOUNT_SETTINGS_KEY_NOT_FOUND,

    ERROR_BUSINESS_EMAIL_NOT_SENT
}
